api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ProjectViewSet,
    LoginView,
    LogoutView,
    UserProfileView,
)

router = DefaultRouter()
router.register(r"projects", ProjectViewSet, basename="project")

urlpatterns = [
    path("", include(router.urls)),
    path("login/", LoginView.as_view(), name="api-login"),
    path("logout/", LogoutView.as_view(), name="api-logout"),
    path("user-profile/", UserProfileView.as_view(), name="user-profile"),
]

centralize_gis_db/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)

urlpatterns = [
    # ADMIN
    path("not-admin/", admin.site.urls),
    # APPS
    path("gis-database/", include("gis_database.urls")),
    path("gis-database/accounts/", include("allauth.urls")),
    path("gis-database/accounts/", include("accounts.urls")),
    path("customer-service/", include("customer_service.urls")),
    path('', include("landingpage.urls")),
    # API
    path("api/v1/", include("api.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
]

if settings.DEBUG:
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

if not settings.IS_PROD:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gis_database/urls.py
from django.urls import path
from . import views

app_name = "gis_database"

urlpatterns = [
    path('', views.home, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("guides/", views.guides, name="guides"),
    path("analytics/", views.analytics, name="analytics"),
    
    path("upload/", views.upload_project, name="upload-project"),
    path("create/", views.create_project, name="create-project"),
    path("project/<int:pk>/details/", views.project_detail, name="project-details"),
    path("project/<int:pk>/analytics/", views.project_analytics, name="project-analytics"),
    path("project/<int:pk>/delete/", views.delete_project, name="project-delete"),
    path("project/<int:pk>/download/", views.download_project, name="download-file"),
    path("project/<int:pk>/update/", views.update_file, name="update-file"),
    
    path("project/<int:project_id>/add-member/", views.add_member, name="add_member"),
    path('project/<int:project_id>/search-users/', views.search_users, name="search_users"),
    path("project/<int:project_id>/remove-member/<int:user_id>/", views.remove_member, name="remove-member"),

    path("user-profile/", views.user_profile, name="user-profile"),

    path("file/delete-all/<int:pk>/", views.delete_file, name="delete-file"),
    
    path("test/", views.test, name="test"),
    path("test-file/", views.test_files, name="test-file"),
    path("guides/qgis/", views.guides_qgis, name="qgis")
]

gis_database/views.py
import os
import zipfile
from io import BytesIO

from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import ensure_csrf_cookie
from django.db.models import Sum
from django.db import transaction
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.contrib.auth.models import User

from .models import Project, File, FileActivity, ProjectMembership
from accounts.models import Profile
from .forms import ProjectForm, CreateProjectForm

from .utils import compute_hash

sidebar_menu = [
    {"label": "Storage", "icon": "database", "url": "/dashboard/"},
    {"label": "Analytics", "icon": "chart-pie", "url": reverse_lazy("analytics")},
    {"label": "Guides", "icon": "notebook-text", "url": reverse_lazy("guides")},
]


# -------------------------------
# Utilities
# -------------------------------
def get_user_storage_context(request):
    uploads = Project.objects.filter(owner=request.user, is_deleted=False).order_by(
        "-created_at"
    )
    paginator = Paginator(uploads, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    total_bytes = sum(
        f.file.size for f in File.objects.filter(project__owner=request.user) if f.file
    )

    try:
        profile = request.user.profile
    except Profile.DoesNotExist:
        profile = None

    if profile and profile.storage_limit_mb > 0:
        remaining_mb = round(profile.remaining_storage_bytes() / (1024 * 1024), 1)
        max_storage = profile.storage_limit_mb
    else:
        remaining_mb = 0
        max_storage = 0

    used_percent = min(
        round((total_bytes / (profile.storage_limit_mb * 1024 * 1024)) * 100, 1),
        100,
    )

    return {
        "page_obj": page_obj,
        "uploads": page_obj,
        "storage_percentage": used_percent,
        "remaining_mb": remaining_mb,
        "max_storage": max_storage,
    }


def unset_latest(user, project, file_name):
    """Helper to unset is_latest for previous files if the are the same hash"""
    File.objects.filter(
        owner=user,
        project=project,
        name=file_name,
        is_latest=True,
    ).update(is_latest=False)


# -------------------------------
# Public Views
# -------------------------------
def home(request):
    return render(request, "pages/home.html")


def guides(request):
    return render(request, "pages/guides.html", {"sidebar_menu": sidebar_menu})


def analytics(request):
    projects = Project.objects.filter(owner=request.user, is_deleted=False)

    context = get_user_storage_context(request)
    file_activities = FileActivity.objects.filter(owner=request.user)
    context.update(
        {
            "file_activities": file_activities,
            "sidebar_menu": sidebar_menu,
        }
    )
    return render(request, "pages/analytics.html", context)


def guides_qgis(request):
    return render(request, "components/guides/qgis.html")


def test_files(request):
    return render(request, "pages/test.html")


def test(request):
    return HttpResponse("<h1>Hello Test</h1>")


# -------------------------------
# Authenticated Views
# -------------------------------


@login_required
@ensure_csrf_cookie
def dashboard(request):

    projects = Project.objects.filter(owner=request.user, is_deleted=False)

    chart_labels = [p.name for p in projects]
    chart_data = [round(p.used_storage_bytes() / (1024 * 1024), 2) for p in projects]

    context = get_user_storage_context(request)
    file_activities = FileActivity.objects.filter(owner=request.user)
    context.update(
        {
            "file_activities": file_activities,
            "chart_labels": chart_labels,
            "chart_data": chart_data,
            "sidebar_menu": sidebar_menu,
        }
    )
    return render(request, "pages/dashboard.html", context)


@login_required
def project_sync(request, pk):
    project = get_object_or_404(Project, pk=pk, owner=request.user)
    return render(
        request, "components/project/_detail-layout.html", {"project": project}
    )


@login_required
def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk, owner=request.user)
    role = project.get_user_role(request.user)
    member = project.membership.select_related("user").all()

    can_manage = project.can_manage(request.user)

    context = {
        "project": project,
        "role": role,
        "members": member,
        "can_manage": can_manage,
    }

    return render(request, "components/project/_detail-layout.html", context)


@login_required
def upload_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST, request.FILES, owner=request.user)

        if form.is_valid():
            uploaded_file = request.FILES["uploaded_file"]

            # size per file validation
            if uploaded_file.size > File.MAX_FILE_SIZE:
                form.add_error("uploaded_file", "File exceeds maximum size (100MB)")
                return render(request, "pages/upload.html", {"form": form})

            # storage quota of the user
            if not request.user.profile.can_store(uploaded_file.size):
                form.add_error("uploaded_file", "Storage limit exceeded during upload.")
                return render(request, "pages/upload.html", {"form": form})

            new_hash = compute_hash(uploaded_file)

            with transaction.atomic():
                project = form.save(commit=False)
                project.owner = request.user
                project.save()

                file_folder = os.path.splitext(uploaded_file.name)[0].replace(" ", "_")

                file_obj = File.objects.create(
                    project=project,
                    owner=request.user,
                    name=uploaded_file.name,
                    file_folder=file_folder,
                    file=uploaded_file,
                    hash=new_hash,
                    version=1,
                    is_latest=True,
                )

                FileActivity.objects.create(
                    file=file_obj,
                    owner=request.user,
                    action="uploaded new file",
                )

                return redirect("dashboard")
    else:
        form = ProjectForm(owner=request.user)

    return render(request, "pages/upload.html", {"form": form})


@transaction.atomic
def create_project(request):
    form = CreateProjectForm(request.POST or None)

    if form.is_valid():
        project = form.save(commit=False)
        project.owner = request.user
        project.save()

        ProjectMembership.objects.get_or_create(
            user=request.user,
            project=project,
            role="admin",
            invited_by=request.user,
        )

        return redirect("dashboard")

    return render(request, "components/project/create-layout.html", {"form": form})


@login_required
def download_project(request, pk):
    """
    Download all latest ProjectFiles of a project as a ZIP.
    """
    project = get_object_or_404(Project, pk=pk, owner=request.user)
    files = project.files.filter(is_latest=True, project__is_deleted=False)

    if not files.exists():
        raise Http404("No files in this project.")

    zip_buffer = BytesIO()
    with zipfile.ZipFile(zip_buffer, "w") as zip_file:
        for pf in files:
            if pf.file:
                stored_name = os.path.basename(pf.file.name)
                base_name, ext = os.path.splitext(stored_name)

                if "_v" in base_name:
                    base_name = base_name.rsplit("_v", 1)[0]

                download_name = f"{base_name}{ext}"

                with pf.file.open("rb") as f:
                    zip_file.writestr(download_name, f.read())

    zip_buffer.seek(0)
    response = HttpResponse(zip_buffer, content_type="application/zip")
    response["Content-Disposition"] = f'attachment; filename="{project.name}.zip"'
    return response


@login_required
def update_file(request, pk):
    project = get_object_or_404(Project, pk=pk, owner=request.user)
    latest_file = project.files.filter(is_latest=True).order_by("-version").first()

    if request.method == "POST":
        form = ProjectForm(request.POST, request.FILES, owner=request.user)

        if form.is_valid():
            uploaded_file = form.cleaned_data["uploaded_file"]
            profile = request.user.profile

            if not profile.can_store(uploaded_file.size):
                # Future modal: storage quota exceeded
                return HttpResponse("Storage quota exceeded", status=400)

            new_hash = compute_hash(uploaded_file)

            with transaction.atomic():
                # Case 1: File with same hash exists -> mark as latest
                existing_file_with_hash = project.files.filter(hash=new_hash).first()
                if existing_file_with_hash:
                    unset_latest(request.user, project, existing_file_with_hash.name)
                    existing_file_with_hash.is_latest = True
                    existing_file_with_hash.save(update_fields=["is_latest"])
                    return redirect("project-detail", pk=project.id)

                # Case 2: Same name, different hash -> version increment
                latest_file_same_name = (
                    project.files.filter(name=uploaded_file.name)
                    .order_by("-version")
                    .first()
                )
                if latest_file_same_name:
                    unset_latest(request.user, project, latest_file_same_name.name)
                    version = latest_file_same_name.version + 1
                    file_folder = latest_file_same_name.file_folder

gis_database/views/dashboard.py
import json

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import ensure_csrf_cookie
from django.db.models import Sum, F
from django.urls import reverse_lazy
from django.core.paginator import Paginator

from ..models import Project, File, FileActivity
from accounts.models import Profile
from ..models import ProjectMembership


def get_user_storage_context(request):
    uploads = Project.objects.filter(owner=request.user, is_deleted=False).order_by(
        "-created_at"
    )
    paginator = Paginator(uploads, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    total_bytes = (
        File.objects.filter(project__owner=request.user).aggregate(total=Sum("size"))[
            "total"
        ]
        or 0
    )

    try:
        profile = request.user.profile
    except Profile.DoesNotExist:
        profile = None

    if profile and profile.storage_limit_mb > 0:
        remaining_mb = round(profile.remaining_storage_bytes() / (1024 * 1024), 1)
        max_storage = profile.storage_limit_mb
    else:
        remaining_mb = 0
        max_storage = 0

    used_percent = min(
        round((total_bytes / (profile.storage_limit_mb * 1024 * 1024)) * 100, 1),
        100,
    )

    return {
        "page_obj": page_obj,
        "uploads": page_obj,
        "storage_percentage": used_percent,
        "remaining_mb": remaining_mb,
        "max_storage": max_storage,
    }


@ensure_csrf_cookie
def dashboard(request):
    projects = Project.objects.filter(owner=request.user, is_deleted=False).annotate(
        used_bytes=Sum("files__size")
    )

    chart_labels = [p.name for p in projects]
    chart_data = [round(p.used_storage_bytes() / (1024 * 1024), 2) for p in projects]

    context = get_user_storage_context(request)
    file_activities = FileActivity.objects.filter(owner=request.user)
    context.update(
        {
            "file_activities": file_activities,
            "chart_labels": chart_labels,
            "chart_data": chart_data,
        }
    )
    return render(request, "pages/dashboard.html", context)


def analytics(request):
    projects = Project.objects.filter(is_deleted=False).prefetch_related(
        "membership__user"
    )

    context = get_user_storage_context(request)

    members_dict = {}

    for project in projects:
        members = project.membership.select_related("user").exclude(user=project.owner)
        for m in members:
            if m.user.id not in members_dict:

                m.all_projects = [
                    up.project
                    for up in ProjectMembership.objects.filter(
                        user=m.user
                    ).select_related("project")
                    if not up.project.is_deleted
                ]
                m.current_projects = [project]
                members_dict[m.user.id] = m
            else:
                members_dict[m.user.id].current_projects.append(project)

        members_list = list(members_dict.values())

    context.update(
        {
            "members": members_list,
        }
    )

    return render(request, "pages/analytics.html", context)

gis_database/views/public_views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

# @login_required
def home(request):
    return render(request, "pages/home.html")


def guides(request):
    return render(request, "pages/guides.html")


def guides_qgis(request):
    return render(request, "components/guides/qgis.html")


def test_files(request):
    return render(request, "pages/test.html")


def test(request):
    return HttpResponse("<h1>Hello Test</h1>")

gis_database/templates/components/dashboard/activity_logs.html
<div class="card bg-neutral shadow-sm p-4 w-full h-full">
    <h3 class="text-lg text-neutral-content font-black mb-5 uppercase">Recent Activities</h3>
    <div class="grid grid-cols-1 gap-2 text-xs">
        {% for activity in file_activities|slice:'4' %}
            <div class="card bg-base-100 p-2 shadow-inner">
                <div class="flex justify-between items-center mb-1">
                    <h4 class="text-xs font-bold text-gray-700">
                        {% if activity.file.project.name %}
                            {{ activity.file.project.name }}
                        {% else %}
                            {{ activity.project_name_snapshot }}
                        {% endif %}
                    </h4>
                    <span class="text-gray-400">{{ activity.created_at|date:'M d, H:i' }}</span>
                </div>
                <div class="text-xs text-gray-600 mb-1">{{ activity.action }}</div>
                <div class="text-xs font-semibold text-gray-800">
                    {% if activity.file %}
                        {{ activity.file.name }}
                    {% elif activity.file_name_snapshot %}
                        {{ activity.file_name_snapshot }}
                    {% endif %}
                </div>
            </div>
        {% empty %}
            <div class="card bg-base-100 p-2 text-center text-gray-500 text-xs shadow-inner">No recent activity found.</div>
        {% endfor %}
    </div>
</div>

gis_database/templates/components/dashboard/file_versions.html
<div class="card bg-base-100 shadow-sm p-6 w-full h-full max-h-[400px] lg:max-h-[400px] flex flex-col overflow-hidden">
    <div class="flex justify-between">
        <h3 class="text-lg font-black mb-2 uppercase flex-none">Files and Version</h3>
        <span class="badge badge-neutral font-black border-none h-6 px-2 text-[10px] tracking-widest uppercase justify-end">
            {{ latest_files|length }} Item/s
        </span>
    </div>
    <div class="flex-1 overflow-y-auto flex flex-col gap-2">
        {% for file in latest_files %}
            <div class="card bg-base-200 px-2 py-1 flex-none">
                <div class="flex justify-between items-center mb-1">
                    <div class="flex text-center items-center gap-5">
                        <span class="p-2 border text-primary rounded-lg">
                            <i data-lucide="file-text"></i>
                        </span>
                        <div class="flex flex-col justify-start text-left">
                            <h4 class="text-sm font-bold text-gray-700">{{ file.name }}</h4>
                            <span class="text-xs">{{ file.uploaded_at }}</span>
                        </div>
                    </div>
                    <form action="{% url 'gis_database:delete-file' file.id %}"
                          method="POST"
                          onsubmit="return confirm('WARNING: This will delete ALL versions of this file from the database and cloud. Proceed?');">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-error btn-outline btn-sm">
                            <i data-lucide="trash-2"></i>
                        </button>
                    </form>
                </div>
            </div>
        {% empty %}
            <span class="card bg-base-200 p-2 text-center">No files uploaded</span>
        {% endfor %}
    </div>
</div>

gis_database/templates/components/dashboard/header.html
<div>
    <h1 class="text-neutral text-3xl md:text-4xl font-black tracking-widest uppercase mb-1">{{ title }}</h1>
    <p class="font-light">{{ subtitle }}</p>
</div>

gis_database/templates/components/dashboard/setting.html
{% extends "_base.html" %}
{% load static %}
{% block content %}
    <div class="flex flex-col gap-5 card bg-base-100 p-5 shadow-sm w-full h-full">
        <h3 class="font-black text-lg tracking-tight uppercase">Settings</h3>
        <div class="space-y-3">
            <div class="flex items-center justify-between bg-base-200 p-4 rounded-lg">
                <div>
                    <p class="font-semibold">Public Access</p>
                    <p class="text-xs opacity-60">Anyone with the link can view this project.</p>
                </div>
                <button class="btn btn-primary">Make Private</button>
            </div>
        </div>
        <div class="space-y-3">
            <div class="bg-base-200 rounded-lg p-4 flex items-center justify-between">
                <div>
                    <p class="font-semibold text-error">Delete Project</p>
                    <p class="text-xs opacity-70">Permanently remove this project and all associated files.</p>
                </div>
                <a href="{% url 'gis_database:project-delete' project.pk %}"
                   class="btn btn-error btn-outline btn-square">
                    <i data-lucide="trash-2" class="w-6 h-6"></i>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

gis_database/templates/components/dashboard/storage_card.html
<div class="card bg-base-100 shadow-sm h-full">
    <div class="card-body justify-center p-5 h-full flex flex-col">
        <span class="text-lg sm:text-xl font-black uppercase">Storage Capacity</span>
        <div class="flex-1 flex flex-col justify-center">
            <div class="flex items-end gap-2 mt-1">
                <span class="text-4xl font-black tracking-tighter">{{ storage_percentage }}%</span>
                <span class="text-sm font-black uppercase text-gray-500">Used</span>
            </div>
            <progress class="progress progress-primary w-full mt-2 h-4"
                      value="{{ storage_percentage }}"
                      max="100"></progress>
            <p class="text-sm font-black mt-2 text-primary">{{ remaining_mb }}MB / {{ max_storage }}MB Available</p>
        </div>
    </div>
</div>

gis_database/templates/components/dashboard/upload_card.html
<div class="card bg-primary text-primary-content shadow-sm h-full">
    <div class="card-body p-5 flex-1">
        <div class="flex flex-col h-full justify-between gap-4">
            <div>
                <h2 class="text-xl lg:text-xl text-white font-black uppercase mb-2">Create a new project</h2>
                <p class="font-bold text-xs text-white tracking-wide opacity-90">Please prepare the files for your project.</p>
            </div>
            <div class="pt-3">
                {% if remaining_mb > 0 %}
                    <a href="{% url 'gis_database:create-project' %}"
                       class="btn btn-neutral px-6 font-black uppercase tracking-widest">Create New</a>
                {% else %}
                    <span class="badge badge-warning p-4 text-xs font-black text-error">Insufficient Storage</span>
                {% endif %}
            </div>
        </div>
    </div>
</div>